### ISSUE TITLE
备用站https链接不信任

### ISSUE THREAD

**Issue by Dedicatus5457** [ariespan-Open/feedback#2]
![捕获0918](https://user-images.githubusercontent.com/78254776/190878758-f1fb420c-8a0a-43b3-ac21-69bf04f94103.PNG)
![捕获091802](https://user-images.githubusercontent.com/78254776/190878762-355d4af0-b24e-497f-bd02-c7fc42c22014.PNG)
rt SSL证书过期

**Comment by Dedicatus5457** [comment]
@majinqiawa

**Comment by majinqiawa** [comment]
有空换掉:)













在 2022-09-18 06:49:18，"Hou Qiyao" ***@***.***> 写道：

@majinqiawa
